services:
  server-client:
    build:
      context: ./
    volumes:
      - ./:/app:z
    environment:
      - PORT=80
      - NODE_ENV=development
      - DB_HOST=postgres-dev
      - DB_PORT=5432
      - DB_NAME=PgBee
      - DB_USER=postgres
      - DB_PASSWORD=password

    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - postgres-dev
    networks:
      - app-network-dev

  postgres-dev:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - app-network-dev

networks:
  app-network-dev:
    driver: bridge

volumes:
  postgres-dev-data:
